version: "2"
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/Webbernet/lint-config/master/.rubocop.yml"
    path: ".rubocop.yml"
  fetch:
  - url: "https://raw.githubusercontent.com/Webbernet/lint-config/master/conf.reek"
    path: "conf.reek"
  fetch:
  - url: "https://raw.githubusercontent.com/Webbernet/lint-config/master/.eslintrc"
    path: ".eslintrc"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  identical-code:
    enabled: true
  similar-code:
    enabled: true
plugins:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  reek:
    enabled: true
  flog:
    enabled: true
  scss-lint:
    enabled: true
  stylelint:
    enabled: true
  grep:
    enabled: true
    config:
      patterns:
        no-set-methods:
          pattern: byebug
          annotation: "Make sure you take out your byebugs!"
          severity: major
          categories: Bug Risk
          content: >
            You know
          path_patterns:
            - "**/*.rb"
  duplication:
    enabled: true
    exclude_patterns:
    - "app/facades/"
    - "app/controllers/"
exclude_patterns:
- spec/**/*
- db/
- config/
- dist/
- "**/vendor/**/*"
- app/src/timesheet_pdf/**/*
