AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'spec/factories/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'lib/tasks/**/*'
    - 'bin/*'

Rails:
  Enabled: true

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "spec/support/shared_examples/**/*.rb"

Metrics/AbcSize:
  Max: 25
  Include:
    - "**/*_spec.rb"

Metrics/LineLength:
  Exclude:
    - "app/src/config/*.rb"
    - 'spec/**/*'

Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
